version: "3"

services:
  arrigt:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
      - .env.local
    ports:
      - 4000:4000
  arrigt-db:
    restart: unless-stopped
    image: postgres:16.1
    env_file:
      - .env
      - .env.local
    ports:
      - ${DB_PORT}:${DB_PORT}

