version: "3"

services:
  app:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
  db:
    restart: unless-stopped
    image: postgres:16.1
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}

