name: Integration Testing

on:
  workflow_dispatch:

jobs:
  run-integration-test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: arrigt
          POSTGRES_USER: arrigt
          POSTGRES_PASSWORD: plupp123
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Install Dependencies
        run: bun install
      - name: Test
        run: bun test:integration
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: integration-report
          path: reports/integration/
          retention-days: 5
      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@v2
        if: always()
        with:
          json-summary-path: ./reports/integration/coverage/coverage-summary.json
          json-final-path: ./reports/integration/coverage/coverage-final.json
          vite-config-path: ./vite.config.integration.ts
          file-coverage-mode: changes
