name: Linting & Formatting

on:
  pull_request:
    branches: [main]
    types: [synchronize]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Install Dependencies
        run: bun install
      - name: Generate Code
        run: bun generate
      - name: Lint
        run: bun lint
  run-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Install Dependencies
        run: bun install
      - name: Format
        run: bun format
