name: Unit Testing

on:
  pull_request:
    branches: [main]
    types: [synchronize]

jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Install Dependencies
        run: bun install
      - name: Test
        run: bun test:unit
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: unit-report
          path: reports/unit/
          retention-days: 5
