name: Unit Testing

on:
  push:

jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Install Dependencies
        run: bun install
      - name: Test
        run: bun test:unit
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: unit-report
          path: reports/unit/
          retention-days: 5
      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@v2
        if: always()
        with:
          json-summary-path: ./reports/unit/coverage/coverage-summary.json
          json-final-path: ./reports/unit/coverage/coverage-final.json
          vite-config-path: ./vite.config.unit.ts
          file-coverage-mode: changes
